{
  "name": "spin2time",
  "version": "1.0.0",
  "description": "Desktop Application of Spin2Time-Program-Suite.",
  "main": "main.js",
  "scripts": {
    "start": "webpack --config webpack.dev.js && electron .",
    "serve:dev": "concurrently \"webpack --config webpack.dev-spa-project.js \" \"electron . --dev\"",
    "deploy:host": "webpack --config webpack.dev.js && electron-packager . --ignore=/saves --asar --prune --out=%cd%/deployment --overwrite --icon=./img/spin2time_logo_transparent_icon.ico",
    "rebuild": "electron-rebuild -f -w bcrypt"
  },
  "repository": {
    "type": "git",
    "url": "git+https://mue17592@bitbucket.org/mue17592/spin2time-win10.git"
  },
  "author": "Leonhard Muellauer and Tobias Pellkvist",
  "license": "ISC",
  "homepage": "https://bitbucket.org/mue17592/spin2time-win10#readme",
  "dependencies": {
    "@mdi/font": "^4.9.95",
    "animate.css": "^3.7.2",
    "bcrypt": "^3.0.7",
    "buefy": "^0.8.10",
    "bulma": "^0.7.5",
    "bulma-calendar": "^6.0.7",
    "bulma-divider": "^0.2.0",
    "bulma-tooltip": "^3.0.2",
    "chart.js": "^2.9.3",
    "custom-electron-titlebar": "^3.1.0",
    "date-and-time": "^0.12.0",
    "date-fns": "^2.9.0",
    "is-online": "^8.2.1",
    "jquery": "^3.4.1",
    "material-design-icons": "^3.0.1",
    "mysql": "^2.17.1",
    "nodemailer": "^6.3.0",
    "open-iconic": "^1.1.1",
    "vue": "^2.6.10",
    "vue-chartjs": "^3.5.0",
    "vue-material-design-icons": "^4.3.0",
    "vue-moment": "^4.1.0",
    "vue-router": "^3.1.3"
  },
  "devDependencies": {
    "callback-loader": "^0.2.4",
    "clean-webpack-plugin": "^3.0.0",
    "concurrently": "^5.0.0",
    "css-loader": "^3.2.0",
    "electron": "^7.1.7",
    "electron-packager": "^14.1.1",
    "electron-rebuild": "^1.8.8",
    "electron-reload": "^1.5.0",
    "file-loader": "^5.0.2",
    "html-webpack-plugin": "^3.2.0",
    "vue-devtools": "^5.1.3",
    "vue-loader": "^15.7.2",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.6.10",
    "webpack": "^4.41.4",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.9.0",
    "webpack-merge": "^4.2.2"
  }
}
